version: "3.8"
services:
  sftp:
    image: atmoz/sftp:latest
    container_name: sftp-server
    ports:
      - "2222:22"  # 호스트 2222 -> 컨테이너 22(SFTP)
    volumes:
      - ./data:/home/foo/upload  # foo 사용자의 업로드 디렉토리와 연결
    environment:
      - SFTP_USERS=foo:pass:1001  # 사용자:비번:UID
    restart: unless-stopped

