{{- if .Values.apache2.enabled }}
apiVersion: v1
kind: Service
metadata:
  name: apache2
  namespace: company-infra
spec:
  type: NodePort
  ports:
    - port: 80
      targetPort: 80
      nodePort: {{ .Values.apache2.nodePort }}
  selector:
    app: apache2
{{- end }}

