apiVersion: v1
kind: Service
metadata:
  name: apache2
  namespace: company-infra
spec:
  type: NodePort
  ports:
    - port: 80
      targetPort: 80
      nodePort: 30880
      protocol: TCP
  selector:
    app: apache2

