apiVersion: v1
kind: ConfigMap
metadata:
  name: apache2-indexhtml
  namespace: company-infra
data:
  index.html: |
    <html>
    <head><title>Apache2 Test Page</title></head>
    <body>
      <h1>Hello from ConfigMap index.html!</h1>
    </body>
    </html>

