<<<<<<< HEAD
=======
{{- if .Values.apache2.enabled }}
>>>>>>> 0d047fc19ce650f73a7d779b5cf966d44f33f113
apiVersion: apps/v1
kind: Deployment
metadata:
  name: apache2
  namespace: company-infra
spec:
  replicas: 1
  selector:
    matchLabels:
      app: apache2
  template:
    metadata:
      labels:
        app: apache2
    spec:
      containers:
        - name: apache2
<<<<<<< HEAD
          image: httpd:2.4-alpine
=======
          image: httpd:2.4
>>>>>>> 0d047fc19ce650f73a7d779b5cf966d44f33f113
          ports:
            - containerPort: 80
          volumeMounts:
            - name: apache2-conf
              mountPath: /usr/local/apache2/conf/httpd.conf
<<<<<<< HEAD
              subPath: httpd.conf
            - name: indexhtml
              mountPath: /usr/local/apache2/htdocs/index.html
              subPath: index.html
=======
              subPath: mywebsite.conf
            - name: webroot
              mountPath: /usr/local/apache2/htdocs
>>>>>>> 0d047fc19ce650f73a7d779b5cf966d44f33f113
      volumes:
        - name: apache2-conf
          configMap:
            name: apache2-config
<<<<<<< HEAD
        - name: indexhtml
          configMap:
            name: apache2-indexhtml
=======
        - name: webroot
          persistentVolumeClaim:
            claimName: apache2-pvc
{{- end }}
>>>>>>> 0d047fc19ce650f73a7d779b5cf966d44f33f113

