<<<<<<< HEAD
=======
{{- if .Values.apache2.enabled }}
>>>>>>> 0d047fc19ce650f73a7d779b5cf966d44f33f113
apiVersion: v1
kind: Service
metadata:
  name: apache2
  namespace: company-infra
spec:
  type: NodePort
  ports:
    - port: 80
      targetPort: 80
<<<<<<< HEAD
      nodePort: 30880
      protocol: TCP
  selector:
    app: apache2
=======
      nodePort: {{ .Values.apache2.nodePort }}
  selector:
    app: apache2
{{- end }}
>>>>>>> 0d047fc19ce650f73a7d779b5cf966d44f33f113

