{{- if .Values.apache2.enabled }}
apiVersion: apps/v1
kind: Deployment
metadata:
  name: apache2
  namespace: company-infra
spec:
  replicas: 1
  selector:
    matchLabels:
      app: apache2
  template:
    metadata:
      labels:
        app: apache2
    spec:
      containers:
        - name: apache2
          image: httpd:2.4
          ports:
            - containerPort: 80
          volumeMounts:
            - name: apache2-conf
              mountPath: /usr/local/apache2/conf/httpd.conf
              subPath: mywebsite.conf
            - name: webroot
              mountPath: /usr/local/apache2/htdocs
      volumes:
        - name: apache2-conf
          configMap:
            name: apache2-config
        - name: webroot
          persistentVolumeClaim:
            claimName: apache2-pvc
{{- end }}

