apiVersion: v1
kind: Service
metadata:
  name: argocd-server
  namespace: company-infra
spec:
  type: NodePort
  ports:
    - port: 80
      targetPort: 8080
      nodePort: {{ .Values.argocd.server.service.nodePort }}
  selector:
    app.kubernetes.io/name: argocd-server

