apiVersion: apps/v1
kind: Deployment
metadata:
  name: elasticsearch
  namespace: company-infra
spec:
  replicas: 1
  selector:
    matchLabels:
      app: elasticsearch
  template:
    metadata:
      labels:
        app: elasticsearch
    spec:
      containers:
        - name: elasticsearch
          image: docker.elastic.co/elasticsearch/elasticsearch:8.13.4
          env:
            - name: discovery.type
              value: single-node
          volumeMounts:
            - name: es-data
              mountPath: /usr/share/elasticsearch/data
          ports:
            - containerPort: 9200
      volumes:
        - name: es-data
          persistentVolumeClaim:
            claimName: elasticsearch-pvc

