apiVersion: v1
kind: Service
metadata:
  name: elasticsearch
  namespace: company-infra
spec:
  type: NodePort
  ports:
    - port: 9200
      targetPort: 9200
      nodePort: {{ .Values.elasticsearch.nodePort }}
  selector:
    app: elasticsearch

