apiVersion: apps/v1
kind: Deployment
metadata:
  name: jenkins
  namespace: company-infra
spec:
  replicas: 1
  selector:
    matchLabels:
      app: jenkins
  template:
    metadata:
      labels:
        app: jenkins
    spec:
      containers:
        - name: jenkins
          image: "{{ .Values.jenkins.controller.image }}:{{ .Values.jenkins.controller.tag }}"
          ports:
            - containerPort: 8080
          env:
            - name: JENKINS_ADMIN_PASSWORD
              value: "{{ .Values.jenkins.controller.adminPassword }}"

