{{- if .Values.logstash.enabled }}
apiVersion: v1
kind: ConfigMap
metadata:
  name: logstash-config
  namespace: company-infra
data:
  logstash.conf: |-
    {{ .Values.logstash.config | nindent 4 }}
{{- end }}

