{{- if .Values.nodeexporter.enabled }}
apiVersion: v1
kind: Service
metadata:
  name: node-exporter
  namespace: company-infra
spec:
  type: NodePort
  ports:
    - port: 9100
      targetPort: 9100
      nodePort: {{ .Values.nodeexporter.nodePort }}
  selector:
    app: node-exporter
{{- end }}

