{{- if .Values.openvpn.enabled }}
apiVersion: v1
kind: ConfigMap
metadata:
  name: openvpn-config
  namespace: company-infra
data:
  server.conf: |-
    {{ .Values.openvpn.config | nindent 4 }}
{{- end }}

