{{- if .Values.openvpn.enabled }}
apiVersion: apps/v1
kind: Deployment
metadata:
  name: openvpn
  namespace: company-infra
spec:
  replicas: 1
  selector:
    matchLabels:
      app: openvpn
  template:
    metadata:
      labels:
        app: openvpn
    spec:
<<<<<<< HEAD
      initContainers:
        - name: openvpn-init
          image: kylemanna/openvpn
          env:
            - name: EASYRSA_BATCH
              value: "1"
          command:
            - /bin/sh
            - -c
            - |
              if [ ! -f /etc/openvpn/ovpn_env.sh ]; then
                echo "[INFO] Initializing openvpn config...";
                ovpn_genconfig -u udp://192.168.56.103:1194
                export EASYRSA_BATCH=1
                ovpn_initpki nopass
              fi
          volumeMounts:
            - name: openvpn-data
              mountPath: /etc/openvpn
          securityContext:
            capabilities:
              add: ["NET_ADMIN"]
            privileged: true
      containers:
        - name: openvpn
          image: kylemanna/openvpn
          env:
            - name: EASYRSA_BATCH
              value: "1"

          ports:
            - containerPort: 1194
          volumeMounts:
            - name: openvpn-data
              mountPath: /etc/openvpn
          securityContext:
            capabilities:
              add: ["NET_ADMIN"]
            privileged: true
      volumes:
        - name: openvpn-data
          persistentVolumeClaim:
            claimName: openvpn-pvc

=======
      containers:
        - name: openvpn
          image: kylemanna/openvpn
          ports:
            - containerPort: 1194
          volumeMounts:
            - name: openvpn-config
              mountPath: /etc/openvpn/server.conf
              subPath: server.conf
            - name: openvpn-data
              mountPath: /etc/openvpn
      volumes:
        - name: openvpn-config
          configMap:
            name: openvpn-config
        - name: openvpn-data
          persistentVolumeClaim:
            claimName: openvpn-pvc
>>>>>>> 0d047fc19ce650f73a7d779b5cf966d44f33f113
{{- end }}

