{{- if .Values.prometheus.enabled }}
apiVersion: v1
kind: Service
metadata:
  name: prometheus
  namespace: company-infra
spec:
  type: NodePort
  ports:
    - port: 9090
      targetPort: 9090
      nodePort: {{ .Values.prometheus.nodePort }}
  selector:
    app: prometheus
{{- end }}

