{{- if .Values.rsnapbackup.enabled }}
apiVersion: v1
kind: PersistentVolumeClaim
metadata:
  name: rsnapbackup-pvc
  namespace: company-infra
spec:
  accessModes: [ "ReadWriteOnce" ]
  resources:
    requests:
      storage: {{ .Values.rsnapbackup.storage }}
  storageClassName: local-path
{{- end }}

