{{- if .Values.samba.enabled }}
apiVersion: v1
kind: PersistentVolume
metadata:
  name: samba-pv
spec:
  capacity:
    storage: {{ .Values.samba.storage }}
  accessModes:
    - ReadWriteOnce
  persistentVolumeReclaimPolicy: Retain
  hostPath:
    path: {{ .Values.samba.hostPath }}
    type: DirectoryOrCreate
{{- end }}
