{{- if .Values.samba.enabled }}
apiVersion: v1
kind: PersistentVolumeClaim
metadata:
  name: samba-pvc
  namespace: company-infra
spec:
  accessModes:
    - ReadWriteOnce
  resources:
    requests:
      storage: {{ .Values.samba.storage }}
<<<<<<< HEAD
  volumeName: samba-pv
  storageClassName: ""
{{- end }}
=======
  storageClassName: local-path
{{- end }}

>>>>>>> 0d047fc19ce650f73a7d779b5cf966d44f33f113
