name: CI/CD Pipeline

on:
  push:
    branches: ["main"]  # 메인 브랜치에 push 시 자동 실행
    paths:
      - "jenkins/**"
      - "values.yaml"
      - ".github/workflows/ci-cd.yaml"

jobs:
  build-and-push-jenkins:
    runs-on: ubuntu-latest

    steps:
      - name: Checkout repository
        uses: actions/checkout@v4

      - name: Log in to DockerHub
        uses: docker/login-action@v3
        with:
          username: ${{ secrets.DOCKERHUB_USERNAME }}
          password: ${{ secrets.DOCKERHUB_TOKEN }}

      - name: Build Jenkins Docker image
        run: docker build -t fw4568/company-infra-jenkins:${{ github.run_number }} ./jenkins

      - name: Push Jenkins Docker image
        run: docker push fw4568/company-infra-jenkins:${{ github.run_number }}

      - name: Update values.yaml Jenkins image tag
        run: |
          sed -i 's/\(repository: fw4568\/company-infra-jenkins\s*tag: \).*/\1${{ github.run_number }}/' values.yaml
          git config --global user.email "fw4568@gmail.com"
          git config --global user.name "github-actions"
          git add values.yaml
          git commit -m "Update Jenkins image tag"
          git push

